name: build-k8s-image

on:
  issue_comment:
    types: [created, edited]

jobs:
  build:
    if: ${{ github.event.issue.pull_request && github.event.issue.state == 'open' && contains(github.event.issue.labels.*.name, 'release') && github.event.comment.body == '/build' }}
    env:
      ISSUE_NUMBER: ${{ github.event.issue.number }}
      ISSUE_LABELS: ${{ join(github.event.issue.labels.*.name, ' ') }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: build image
      run: make `echo ${ISSUE_LABELS} | sed 's/release//g' | sed 's/v//g'`
    - name: start e2e test
      uses: actions/github-script@v4.0.2
      with:
        github-token: ${{ secrets.WORKFLOW_TOKEN }}
        script: |
          (async () => {
            await require('./hack/github/action-lib').commentForE2E(github);
          })();