name: build-k8s-image

on:
  issue_comment:
    types: [created, edited]

jobs:
  e2e:
    runs-on: macos-latest
    if: ${{ github.event.issue.pull_request && contains(github.event.issue.labels.*.name, "release") && github.event.comment.body == "/e2e" }}
    env:
      ISSUE_NUMBER: ${{ github.event.issue.number }}
      ISSUE_LABELS: ${{ join(github.event.issue.labels.*.name, ' ') }}
    steps:
    - uses: actions/checkout@v2
    - name: validate version
      uses: actions/github-script@v4.0.2
      with:
        script: |
          (async () => {
            const kubeVersions = await require('hack/github/action-lib').readKubeVersionFromLabels();
            require('fs').appendFileSync(process.env.GITHUB_ENV, "LATEST_KUBE_VERSION=" + kubeVersions[0]);
          })();
    - name: e2e test
      run: |
        vagrant plugin install vagrant-scp
        mkdir -p /tmp/lan
        curl -skL https://raw.githubusercontent.com/warm-metal/vagrant-lan/master/gateway/Vagrantfile -o /tmp/lan/Vagrantfile
        pushd /tmp/lan
        vagrant up
        popd
        pushd test/k8s-e2e
        vagrant up
        vagrant ssh k8s-e2e-m1 -c 'sudo -E sonobuoy run --mode=certified-conformance --wait'
        REPORT=$(vagrant ssh k8s-e2e-m1 -c 'sudo -E sonobuoy retrieve' 2>/dev/null)
        vagrant scp k8s-e2e-m1:/home/vagrant/${REPORT} ../../sonobuoy.tar.gz
        popd
    - name: commit conformance report
      uses: actions/github-script@v4.0.2
      env:
        PR_OWNER: ${{ secrets.WORKFLOW_PR_OWNER }}
      with:
        github-token: ${{ secrets.WORKFLOW_TOKEN }}
        script: |
          (async () => {
            await require('hack/github/action-lib').commitRootFile(process.env.GITHUB_REF, { path: "sonobuoy.tar.gz" }, "sonobuoy report for version " + process.env.LATEST_KUBE_VERSION);
            await require('hack/github/action-lib').commentForSizeCalc();
          })()