name: new-release-pr

on:
  issues:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !github.event.issue.pull_request && contains(github.event.issue.labels.*.name, "release") }}
    env:
      ISSUE_NUMBER: ${{ github.event.issue.number }}
      ISSUE_LABELS: ${{ join(github.event.issue.labels.*.name, ' ') }}
    steps:
      - uses: actions/checkout@v2
      - name: create PR
        uses: actions/github-script@v4.0.2
        with:
          github-token: ${{ secrets.WORKFLOW_TOKEN }}
          script: |
            (async () => {
              await require('hack/github/action-lib').createPRForNewReleases();
              await require('hack/github/action-lib').commentForImageBuilding();
            })();