name: nightly-k8s-release-check

on:
  schedule:
    # "Minute [0,59]" "Hour [0,23]" "Day of the month [1,31]" "Month of the year [1,12]" "Day of the week ([0,6] with 0=Sunday)"
    - cron: '0 0 * * 2-6'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: check latest releases
        uses: actions/github-script@v4.0.2
        with:
          github-token: ${{ secrets.WORKFLOW_TOKEN }}
          script: |
            (async () => {
              await require('hack/github/action-lib').checkUpstreamRelease();
            })();